# Generated by Django 4.2.2 on 2023-10-26 09:35

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1000, 1000], upload_to=''),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image_original',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
