# Generated by Django 4.2.2 on 2023-10-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gameuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNum', models.IntegerField()),
                ('mmr', models.IntegerField()),
                ('nickname', models.CharField(max_length=90)),
                ('rank', models.IntegerField()),
                ('totalGames', models.IntegerField()),
                ('winrate', models.DecimalField(decimal_places=1, max_digits=6)),
                ('averageKills', models.DecimalField(decimal_places=2, max_digits=6)),
                ('updatedate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamenumber', models.IntegerField()),
                ('user', models.CharField(max_length=90)),
                ('character', models.IntegerField()),
                ('beforemmr', models.IntegerField()),
                ('aftermmr', models.IntegerField()),
                ('gamerank', models.IntegerField()),
                ('playerkill', models.IntegerField()),
                ('playerAss', models.IntegerField()),
                ('mosterkill', models.IntegerField()),
                ('startDtm', models.DateTimeField()),
                ('mmrGain', models.IntegerField()),
                ('damageToPlayer', models.IntegerField(blank=True, default=0)),
                ('damageToMonster', models.IntegerField(blank=True, default=0)),
                ('premaid', models.IntegerField(blank=True, default=0)),
                ('useWard', models.IntegerField(blank=True, default=0)),
                ('useConsole', models.IntegerField(blank=True, default=0)),
                ('item0', models.IntegerField(blank=True, default=0)),
                ('item0_grade', models.CharField(blank=True, max_length=80)),
                ('item1', models.IntegerField(blank=True, default=0)),
                ('item1_grade', models.CharField(blank=True, max_length=80)),
                ('item2', models.IntegerField(blank=True, default=0)),
                ('item2_grade', models.CharField(blank=True, max_length=80)),
                ('item3', models.IntegerField(blank=True, default=0)),
                ('item3_grade', models.CharField(blank=True, max_length=80)),
                ('item4', models.IntegerField(blank=True, default=0)),
                ('item4_grade', models.CharField(blank=True, max_length=80)),
                ('tier', models.CharField(blank=True, max_length=80)),
                ('grade', models.CharField(blank=True, max_length=80)),
                ('rp', models.CharField(blank=True, max_length=80)),
            ],
        ),
    ]
