# Generated by Django 4.2.2 on 2023-09-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gameuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNum', models.IntegerField()),
                ('mmr', models.IntegerField()),
                ('nickname', models.CharField(max_length=90)),
                ('rank', models.IntegerField()),
                ('totalGames', models.IntegerField()),
                ('winrate', models.DecimalField(decimal_places=1, max_digits=6)),
                ('averageKills', models.DecimalField(decimal_places=2, max_digits=6)),
                ('updatedate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamenumber', models.IntegerField()),
                ('user', models.CharField(max_length=90)),
                ('character', models.IntegerField()),
                ('beforemmr', models.IntegerField()),
                ('aftermmr', models.IntegerField()),
                ('gamerank', models.IntegerField()),
                ('playerkill', models.IntegerField()),
                ('playerAss', models.IntegerField()),
                ('mosterkill', models.IntegerField()),
                ('startDtm', models.DateTimeField()),
                ('mmrGain', models.IntegerField()),
                ('damageToPlayer', models.IntegerField(blank=True, default=0)),
                ('damageToMonster', models.IntegerField(blank=True, default=0)),
                ('premaid', models.IntegerField(blank=True, default=0)),
                ('useWard', models.IntegerField(blank=True, default=0)),
                ('useConsole', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
