# Generated by Django 4.2.2 on 2023-10-11 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerecord', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='RP',
            new_name='rp',
        ),
    ]
