# Generated by Django 4.2.2 on 2023-10-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='bestWeapon',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='record',
            name='escapeState',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='tacticalSkillGroup',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='record',
            name='tacticalSkillLevel',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
