# Generated by Django 4.2.2 on 2023-10-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerecord', '0002_record_bestweapon_record_escapestate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='traitFirstCore',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='record',
            name='traitFirstSub1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='traitFirstSub2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='traitSecondSub1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='traitSecondSub2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
