# Generated by Django 4.2.2 on 2023-09-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerecord', '0002_record_item0_record_item1_record_item2_record_item3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='item0_grade',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='record',
            name='item1_grade',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='record',
            name='item2_grade',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='record',
            name='item3_grade',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='record',
            name='item4_grade',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
