# Generated by Django 4.2.2 on 2023-09-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerecord', '0003_record_item0_grade_record_item1_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='RP',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='record',
            name='grade',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='record',
            name='tier',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
