# Generated by Django 4.2.2 on 2023-10-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerecord', '0003_record_traitfirstcore_record_traitfirstsub1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatuse', models.CharField(blank=True, max_length=80)),
                ('nick1', models.CharField(blank=True, max_length=80)),
                ('use_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
