# Generated by Django 4.2.2 on 2023-10-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerecord', '0005_record_matchingmode_record_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='season',
            field=models.IntegerField(blank=True, default=19, null=True),
        ),
    ]
