# Generated by Django 4.2.2 on 2023-10-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerecord', '0006_gameuser_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='versionMajor',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
    ]
