# Generated by Django 4.2.2 on 2023-09-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('attack', models.DecimalField(decimal_places=3, max_digits=6)),
                ('hp', models.DecimalField(decimal_places=3, max_digits=6)),
                ('hpregen', models.DecimalField(decimal_places=3, max_digits=6)),
                ('stamina', models.DecimalField(decimal_places=3, max_digits=6)),
                ('stregen', models.DecimalField(decimal_places=3, max_digits=6)),
                ('defense', models.DecimalField(decimal_places=3, max_digits=6)),
                ('atkspeed', models.DecimalField(decimal_places=3, max_digits=6)),
                ('speed', models.DecimalField(decimal_places=3, max_digits=6)),
                ('koreanname', models.CharField(blank=True, max_length=80)),
                ('RPfor7days', models.IntegerField(blank=True, default=0)),
                ('RPeff', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('trygame7days', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemnumber', models.IntegerField(blank=True, default=0)),
                ('grade', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
    ]
