# Generated by Django 4.2.2 on 2023-10-11 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='RPeff',
            new_name='rpeff',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='RPfor7days',
            new_name='rpfor7days',
        ),
    ]
