# Generated by Django 4.2.2 on 2023-10-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_rename_rpeff_character_rpeff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='rpeff',
            new_name='RPeff',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='rpfor7days',
            new_name='RPfor7days',
        ),
    ]
